[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dev-mcp"
version = "0.8.3"
description = "A command-line tool to run the ai-tracker.sh script."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp",
    "pip>=25.3",
    "ruff",
]

[project.scripts]
dev-mcp = "dev_mcp.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
dev_mcp = ["tools/ai-tracker.sh"]
